"""migrate_phone_to_email_2fa

Revision ID: 931fe5f881a6
Revises: 9b929c446a45
Create Date: 2026-07-09 01:51:07.690260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '931fe5f881a6'
down_revision: Union[str, None] = '9b929c446a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otp_verifications_email'), 'email_otp_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_otp_verifications_id'), 'email_otp_verifications', ['id'], unique=False)
    op.drop_index('ix_phone_otp_verifications_id', table_name='phone_otp_verifications')
    op.drop_index('ix_phone_otp_verifications_phone_number', table_name='phone_otp_verifications')
    op.drop_table('phone_otp_verifications')
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'is_phone_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'is_2fa_enabled')
    op.create_table('phone_otp_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='phone_otp_verifications_pkey')
    )
    op.create_index('ix_phone_otp_verifications_phone_number', 'phone_otp_verifications', ['phone_number'], unique=False)
    op.create_index('ix_phone_otp_verifications_id', 'phone_otp_verifications', ['id'], unique=False)
    op.drop_index(op.f('ix_email_otp_verifications_id'), table_name='email_otp_verifications')
    op.drop_index(op.f('ix_email_otp_verifications_email'), table_name='email_otp_verifications')
    op.drop_table('email_otp_verifications')
    # ### end Alembic commands ###
