"""add_phone_otp_and_user_phone_columns

Revision ID: 9b929c446a45
Revises: 589ef280e83a
Create Date: 2026-07-06 02:07:58.304520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b929c446a45'
down_revision: Union[str, None] = '589ef280e83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otp_verifications_id'), 'phone_otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_phone_otp_verifications_phone_number'), 'phone_otp_verifications', ['phone_number'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_phone_verified = FALSE")
    op.alter_column('users', 'is_phone_verified', nullable=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_phone_otp_verifications_phone_number'), table_name='phone_otp_verifications')
    op.drop_index(op.f('ix_phone_otp_verifications_id'), table_name='phone_otp_verifications')
    op.drop_table('phone_otp_verifications')
    # ### end Alembic commands ###
