"""add_analyses_composite_index

Revision ID: e82f1b490a12
Revises: f1f022833328
Create Date: 2026-09-09 14:30:00.000000

"""
from typing import Sequence, Union
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e82f1b490a12'
down_revision: Union[str, None] = 'f1f022833328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_analyses_contract_id_analysis_type',
        'analyses',
        ['contract_id', 'analysis_type'],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_contract_id_analysis_type', table_name='analyses')
    # ### end Alembic commands ###
