"""add_data_retention_days_to_users

Revision ID: f1f022833328
Revises: d68a24c04ff1
Create Date: 2026-09-07 22:55:05.738568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f022833328'
down_revision: Union[str, None] = 'd68a24c04ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_retention_days')
    # ### end Alembic commands ###
